#include "problem_002.h"
#include <stdio.h>

/* Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 *
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */
void problem_002()
{
    int nums[3] = {1, 2, 3};
    int i = 2;
    int sum = 2;
#define MAX_FIBONACCI_VALUE 4000000
    
    while(1)
    {
        // generate a new fibonacci value in the oldest index of the array
        i++;
        nums[(i)%3] = nums[(i-1)%3] + nums[(i-2)%3];

        //break out if we meet or exceed 4,000,000
        if(nums[i%3] >= 4000000)
            break;

        // check if it is even and add it to the sum
        if(nums[i%3]%2 == 0) // even case
            sum += nums[i%3];// add it to the sum
    }
    printf("The answer to problem 002 is: %d\n", sum);
}
