#include "problem_002.h"
#include <stdio.h>          // printf
#include <stdlib.h>         // EXIT_SUCCESS
#include <string.h>         // strdup
#include <time.h>           // clock() utils
#include <stdbool.h>        // true, false

#define MAX_FIBONACCI_VALUE 4000000
/* Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 *
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */
int problem_002(problem_solution * ps)
{
    clock_t start, end;
    double cpu_time_used_ms;
    ps->problem_number = 2U;
    ps->problem_statement = strdup("Each new term in the Fibonacci sequence is"
            " generated by adding the previous two terms. By starting with 1 "
            "and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55,"
            " 89. By considering the terms in the Fibonacci sequence whose "
            "values do not exceed four million, find the sum of the "
            "even-valued terms.");

    int nums[3] = {1, 2, 3};
    int i = 2;
    int sum = 2;

    start = clock();
    while(true)
    {
        // generate a new fibonacci value in the oldest index of the array
        i++;
        nums[(i)%3] = nums[(i-1)%3] + nums[(i-2)%3];

        //break out if we meet or exceed 4,000,000
        if(nums[i%3] >= 4000000)
            break;

        // check if it is even and add it to the sum
        if(nums[i%3]%2 == 0) // even case
            sum += nums[i%3];// add it to the sum
    }
    end = clock();
    cpu_time_used_ms = 1000.0 * ((double)(end-start)) / CLOCKS_PER_SEC;
    ps->cpu_time_ms = cpu_time_used_ms;
    
    char buf[PE_SOLUTION_BUFFER_LEN];
    int ret;
    /* natural language solution */
    ret = snprintf(buf, sizeof buf, 
            "The sum of even-valued Fibbonaci terms below %d is %d", 
            MAX_FIBONACCI_VALUE, sum);
    if((ret == (int)(sizeof buf)) || (ret < 0))
    {
        perror("project_euler: Problem 002:");
        printf("Error: Problem 002: snprintf error\n");
        return EXIT_FAILURE;        
    }
    ps->natural_language_solution = strndup(buf, (sizeof buf) - 1);

    /* numeric string solution */
    ret = snprintf(buf, sizeof buf, "%d", sum);
    if((ret == (int)(sizeof buf)) || (ret < 0))
    {
        perror("project_euler: Problem 002:");
        printf("Error: Problem 002: snprintf error\n");
        return EXIT_FAILURE;        
    }
    ps->numerical_solution = strndup(buf, (sizeof buf) - 1);
    return EXIT_SUCCESS;
}
