name: make check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GMP
      run: |
        wget -v https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz
        tar -xf gmp-6.3.0.tar.xz
        cd gmp-6.3.0/
        ./configure
        make
        sudo make install
        cd ..

    - name: Install libprimesieve
      run: sudo apt install libprimesieve-dev

    - name: Clean
      run: make clean

    - name: Run make without the ctags generation and stuff
      run: make check
