name: make check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GMP
      run: sudo apt install libgmp-dev

    - name: Install libprimesieve
      run: sudo apt install libprimesieve-dev

    - name: Clean
      run: make clean

    - name: Run make without the ctags generation and stuff
      run: make check
